###Register
POST http://localhost:5000/api/admin/register
Content-Type: application/json

{
    "username": "superadmin1",
    "email": "superadmin1@gmail.com",
    "password": "superadmin1",
    "role": "superAdmin"
}


###Login
POST http://localhost:5000/api/admin/login
Content-Type: application/json

{
    "username": "superadmin",
    "password": "superadmin"
}



###GetPosts
GET http://localhost:5000/api/admin/getPosts
Content-Type: application/json




###GetUsers
GET http://localhost:5000/api/admin/getUsers
Content-Type: application/json


###GetAdmins
GET http://localhost:5000/api/admin/getAdmins
Content-Type: application/json


###VerifyPost
PUT http://localhost:5000/api/admin/verifyPost/6837150fae29c6f4fb8f37e3
Content-Type: application/json


###Logout
POST http://localhost:5000/api/admin/logout
Content-Type: application/json


###Update user
PUT http://localhost:5000/api/users/68346778e3f8136a8c44da96
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}




###Create post
POST http://localhost:5000/api/posts
Content-Type: application/json

{
    "postData": {
        "title": "title2",
        "price": 233,
        "images": [
            "",
            ""
        ],
        "address": "address2",
        "city": "city2",
        "bedroom": 10,
        "bathroom": 5,
        "type": "rent",
        "property": "apartment",
        "latitude": "51.5074",
        "longitude": "-0.1278"
    },
    "postDetail": {
        "desc": "Desc 1",
        "utilities": "Owner is responsible",
        "pet": "Allowed",
        "income": "3x income",
        "size": 88,
        "school": 1200,
        "bus": 800,
        "restaurant": 1500
    }
}




###Get posts
GET  http://localhost:5000/api/posts
Content-Type: application/json



###Get post
GET  http://localhost:5000/api/posts/6837150fae29c6f4fb8f37e3
Content-Type: application/json



###Delete post
DELETE http://localhost:5000/api/posts/6836f5e2fe0e99cf4d518606
Content-Type: application/json


###Get chat
GET http://localhost:5000/api/chats/683cae37eb401f0109fd6c5b
Content-Type: application/json



###Add chat
POST http://localhost:5000/api/chats
Content-Type: application/json

{
    "receiverId": "68346778e3f8136a8c44da96"
}
